---
- name: linshare lib dir exists
  file: path="{{ linshare_lib }}" state=directory owner=tomcat group=tomcat

- name: download linshare
  get_url: url="{{ linshare_url }}" dest="{{ linshare_war }}" owner=tomcat group=tomcat
  notify: restart tomcat

- name: create linshare db schema
  shell:  PGPASSWORD={{ linshare_pass }} unzip -c {{ linshare_war }} WEB-INF/classes/sql/postgresql/createSchema.sql | psql -h {{ linshare_pg_host }} -U {{ linshare_user }} && touch tee {{ linshare_tmp_dir }}/created_schema
  sudo: yes
  sudo_user: postgres
  args:
    creates: "{{ linshare_tmp_dir }}/created_schema"

- name: import linshare db
  shell:  PGPASSWORD={{ linshare_pass }} unzip -c {{ linshare_war }} WEB-INF/classes/sql/postgresql/import-postgresql.sql | psql -h {{ linshare_pg_host }} -U {{ linshare_user }} && touch tee {{ linshare_tmp_dir }}/imported-postgres-tables
  sudo: yes
  sudo_user: postgres
  args:
    creates: "{{ linshare_tmp_dir }}/imported-postgres-tables"

- name: linshare conf dir exists
  file: path="{{ linshare_conf_dir }}" state=directory

- name: extract default linshare conf
  shell: unzip -o -j -d {{ linshare_conf_dir }} {{ linshare_war }} WEB-INF/classes/{linshare,log4j}.*
  args:
    creates: "{{ linshare_conf_dir }}/log4j.properties"

- name: configure linshare
  shell: sed -e 's/^mail.smtp.host=smtp.yourdomain.com/mail.smtp.host={{ linshare_smtp_host }}/' -e 's/^mail.smtp.port=.*/mail.smtp.port=25/' -e 's/^mail.smtp.auth.needed=.*/mail.smtp.auth.needed=false/' -e 's/^linshare.db.username=.*/linshare.db.username={{ linshare_user }}/' -e 's/^linshare.db.password=.*/linshare.db.password={{ linshare_pass }}/' -e 's/^linshare.db.driver.class=.*/linshare.db.driver.class=org.postgresql.Driver/' -e 's/^linshare.db.url=.*/linshare.db.url=jdbc:postgresql:\/\/localhost:5432\/linshare/' -e 's/^linshare.db.dialect=.*/linshare.db.dialect=org.hibernate.dialect.PostgreSQLDialect/' -e 's/^linshare.files.directory=.*/linshare.files.directory=\/var\/lib\/linshare/' {{ linshare_conf_dir }}/linshare.properties.sample > {{ linshare_conf_dir }}/linshare.properties
  args:
    creates: "{{ linshare_conf_dir }}/linshare.properties"

- name: erase sample linshare conf
  file: path="{{ linshare_conf_dir }}/linshare.properties.sample" state=absent

