---
- name: linshare lib dir exists
  file: path="{{ linshare_lib }}" state=directory owner=tomcat group=tomcat

- name: download linshare
  get_url: url="{{ linshare_url }}" dest="{{ linshare_war }}" owner=tomcat group=tomcat
  notify: restart tomcat

- name: create linshare db schema
  shell:  PGPASSWORD={{ linshare_pass }} unzip -c {{ linshare_war }} WEB-INF/classes/sql/postgresql/createSchema.sql | psql -h {{ linshare_pg_host }} -U {{ linshare_user }} && touch tee {{ linshare_tmp_dir }}/created_schema
  sudo: yes
  sudo_user: postgres
  args:
    creates: "{{ linshare_tmp_dir }}/created_schema"

- name: import linshare db
  shell:  PGPASSWORD={{ linshare_pass }} unzip -c {{ linshare_war }} WEB-INF/classes/sql/postgresql/import-postgresql.sql | psql -h {{ linshare_pg_host }} -U {{ linshare_user }} && touch tee {{ linshare_tmp_dir }}/imported-postgres-tables
  sudo: yes
  sudo_user: postgres
  args:
    creates: "{{ linshare_tmp_dir }}/imported-postgres-tables"
