---
- name: linshare lib dir exists
  file: path=/var/lib/linshare state=directory owner=tomcat group=tomcat

- name: download linshare
  get_url: url="{{ linshare_url }}" dest="{{ linshare_war }}" owner=tomcat group=tomcat
