---
- name: linshare lib dir exists
  file: path=/var/lib/linshare state=directory owner=tomcat group=tomcat

- name: download linshare
  get_url: url=https://forge.linshare.org/attachments/download/378/linshare-1.5.8-SSO.war dest=/var/lib/tomcat/webapps/linshare.war owner=tomcat group=tomcat
