---
- name: Install Postgres
  yum: name=postgresql-jdbc state=present

- name: Add linshare db/user to pg_hba
  lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf regexp="host\s+{{ linshare_db }},{{ linshare_db_data }}\s+{{ linshare_user }}\s+127.0.0.1/32\s+md5" line="host {{ linshare_db }},{{ linshare_db_data }} {{ linshare_user }} 127.0.0.1/32 md5" insertbefore=BOF
  notify: restart postgresql

- name: creates linshare tmp dir
  file: path="{{ linshare_tmp_dir }}" state=directory mode=0777

- name: Create linshare db user
  shell: createuser -DSREil {{ linshare_user }} && touch {{ linshare_tmp_dir }}/created_db_user
  sudo: yes
  sudo_user: postgres
  args:
    creates: "{{ linshare_tmp_dir }}/created_db_user"

- name: set password for linshare db user
  shell: echo "ALTER USER {{ linshare_user }} WITH PASSWORD '{{ linshare_user }}';" | psql && touch {{ linshare_tmp_dir }}/set-pg_user_password
  sudo: yes
  sudo_user: postgres
  args:
    creates: "{{ linshare_tmp_dir }}/set-pg_user_password"

- name: adds french support
  shell: yum groupinstall "French Support" && touch {{ linshare_tmp_dir }}/added_french_locale
  args:
    creates: "{{ linshare_tmp_dir }}/added_french_locale"

- name: creates linshare db
  shell: createdb -E UTF8 -D pg_default --lc-collate=fr_FR.utf8 --lc-ctype=fr_FR.utf8 -T template0 -O {{ linshare_user }} {{ linshare_db }} && touch {{ linshare_tmp_dir }}/created_linshare_db
  sudo: yes
  sudo_user: postgres
  args:
    creates: "{{ linshare_tmp_dir }}/created_linshare_db"
