---
- name: Install Postgres
  yum: name={{item}} state=present
  with_items:
    - postgresql
    - postgresql-jdbc
    - postgresql-server

- name: Initdb
  command: service postgresql initdb
  args:
    creates: /var/lib/pgsql/data/postgresql.conf

- name: Start PostgreSQL and enable at boot
  service: name=postgresql enabled=yes state=started

- name: Ensure PostgreSQL is listening on all localhost
  lineinfile: dest=/var/lib/pgsql/data/postgresql.conf regexp='^#?listen_addresses\s*=' line="listen_addresses = '127.0.0.1'" state=present
  notify: restart postgresql
